# Generated by Django 3.0.3 on 2020-02-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Fall'), (2, 'Spring')])),
                ('moduleCode', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateProf.Module')),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateProf.Professor')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateProf.User')),
            ],
        ),
        migrations.CreateModel(
            name='Prof_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleID', models.ManyToManyField(to='rateProf.Module')),
                ('profID', models.ManyToManyField(to='rateProf.Professor')),
            ],
        ),
    ]
