# Generated by Django 3.0.3 on 2020-03-12 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleCode', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='moduleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'One'), (2, 'Two')])),
                ('year', models.CharField(max_length=4)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateProf.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('prof_id', models.CharField(default='0', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateProf.moduleInstance')),
                ('profID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateProf.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='professor',
            field=models.ManyToManyField(to='rateProf.Professor'),
        ),
    ]
